version: "3.9"

services:
  nodejs:
    build:
      context: .
      target: prod
    restart: unless-stopped
    deploy:
      replicas: 3
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx_proxy:v1
    ports:
      - 8080:80
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - nodejs